### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by eonkleynhans** [kofrasa/mingo#390] opened 2023-10-16 13:56 UTC
# Description:
On attempting to use the mingo library in a svelte-kit project, a response code 500 gets returned with the following error:
```
app.53d1804f.js:1 TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Tt (2.5f860fc3.js:1:1524)
    at n (2.5f860fc3.js:1:1843)
    at n (2.5f860fc3.js:1:1776)
    at ge (2.5f860fc3.js:1:1868)
    at new T (2.5f860fc3.js:1:10112)
    at T.init (2.5f860fc3.js:1:10140)
    at 2.5f860fc3.js:1:26119
handleError @ app.53d1804f.js:1
```

The error only occurs when building the app with `npm run build`, and then serving with `npm preview`.

# Steps to reproduce:
- Run npm create svelte@latest my-app:
- Select skeleton project.
- Select typescript using Javascript with JSDoc comments.
- Select add ESLint for code linting, prettier for code formatting, add Playwright for browser testing, add Vitest for unit testing.
- Run npm install mingo.
- Run npm install @sveltejs/adapter-static.
- Modify the adapter import in svelte.config.js to import adapter from '@sveltejs/adapter-static' (The adapter we use to build).
-  Add +layout.js file to routes and add export const prerender = true; to this file
- Create a .js file (like helpers.js) inside the src directory of your project and add the follwing:

```
import mingo from "mingo";
export default mingo;
```

- Inside any +page.svelte file inside src/routes add the import for your helpers (or mingo):

```
<script>
    	import helpers from '../helpers';
</script>
```

- Execute `npm run build` then `npm run preview` and open your app

**Comment by maxnowack** [comment] 2023-10-16 15:15
I've experienced the same or at least a similar bug in my nextjs application. I've already analyzed it a bit, but haven't opened a PR because I haven't been able to extend the test cases for testing my fix, nor have I been able to provide a simple reproduction environment for the bug.

What I've found so far is that the bug was introduced in `v6.4.7` and it occurs in the [`isTypedArray` function](https://github.com/kofrasa/mingo/blob/d17d51718b94aabd4bb128b669d6b7a3480be6ce/src/util.ts#L154-L157).
I did some digging and found out that my build environment overwrites the `[Symbol.toStringTag]` of an object that is a module (e.g. `Object.defineProperty({ ... }, Symbol.toStringTag, { value: "Module" })`). This breaks the [`isObject`](https://github.com/kofrasa/mingo/blob/d17d51718b94aabd4bb128b669d6b7a3480be6ce/src/util.ts#L215) check and therefore calls the `isTypedArray` function from [`cloneDeep`](https://github.com/kofrasa/mingo/blob/d17d51718b94aabd4bb128b669d6b7a3480be6ce/src/util.ts#L186).

A possible fix would be to test if the constructor is defined:
```patch
const isTypedArray = (v: AnyVal): boolean => {
+  const ctor = getConstructor(v);
+  const proto = ctor && Object.getPrototypeOf(ctor) as Callback;
-  const proto = Object.getPrototypeOf(getConstructor(v)) as Callback;
  return proto && proto.name === "TypedArray";
};
```

But this will only fix the symptom of the error, not the root cause which is in `isObject`.

**Comment by eonkleynhans** [comment] 2023-10-16 16:13
I've just tested through all the versions and the latest working one for our case seems to be 5.1.0

**Comment by maxnowack** [comment] 2023-10-16 16:15
Okay, then it might be a different bug in my case

**Comment by kofrasa** [comment] 2023-10-16 17:46
Thanks for reporting this issue. Doing a quick comparison between versions, the `isObject` function hasn't changed since `5.1.0`.  The `isTypeArray` function is recent addition to support deep cloning typed arrays when present. 

There is a guard to ensure `null` and `undefined` values aren't passed directly to `Object.getPrototypeOf` by delegating to internal classes `Null` and `Undefined` to represent them. This ensures their constructors always exist.

Besides those two, I am unaware of an object in JS that would not have a constructor. 

Can you confirm whether the transpiled JS maintains all checks?

**Comment by maxnowack** [comment] 2023-10-17 11:42
It's possible to actively overwrite the prototype or set it to `null`. It seems that vite is doing something like that for modules:
<img width="312" alt="image" src="https://github.com/kofrasa/mingo/assets/186073/5dbd29dc-b2ac-4750-8897-0077f1e33dc3">

I've put the reproduction example from @eonkleynhans, mentioned in the first post, in a repository for make testing easier: https://github.com/maxnowack/mingo-reproduction-390

**Comment by maxnowack** [comment] 2023-10-19 09:15
Refactoring the `isObject` method to also work on these types of objects is a bit hard and I wasn't able to figure out a general solution for that.
Spreading the imported `[object Module]` into a plain object when calling `useOperators` resolves the `TypeError`.
I proposed a fix in #391

**Comment by maxnowack** [comment] 2023-10-19 14:32
As I mentioned [here](https://github.com/kofrasa/mingo/pull/391#issuecomment-1770912159), things were already fixed by https://github.com/kofrasa/mingo/commit/254afa6c108289e9b64e6de21d1bd2e0b2fb4dc5

**Closed** 2023-10-19 16:47 UTC

**Comment by maxnowack** [comment] 2023-10-20 15:00
@kofrasa don't forget to publish the changes to npm 🙂
